Shop/Models/Kindergarten/KindergartenCreateUpdateViewModel.cs
namespace Shop.Models.Kindergarten
{
    public class KindergartenCreateUpdateViewModel
    {
        public Guid? Id { get; set; }
        public string? GroupName { get; set; }
        public int? ChidlrenCount { get; set; }
        public string? KindergartenName { get; set; }
        public string? TeacherName { get; set; }
        public List<IFormFile> Files { get; set; }
        public List<KindergartenImageViewModel> Image { get; set; }
            = new List<KindergartenImageViewModel>();
        public DateTime? CreatedAt { get; set; } = DateTime.UtcNow;
        public DateTime? UpdatedAt { get; set; } = DateTime.UtcNow;
    }
}

Shop/Models/Kindergarten/KindergartenDeleteViewModel.cs
namespace Shop.Models.Kindergarten
{
    public class KindergartenDeleteViewModel
    {
        public Guid? Id { get; set; }
        public string? GroupName { get; set; }
        public int? ChidlrenCount { get; set; }
        public string? KindergartenName { get; set; }
        public string? TeacherName { get; set; }
        public List<KindergartenImageViewModel> Image { get; set; }
            = new List<KindergartenImageViewModel>();
        public DateTime? CreatedAt { get; set; } = DateTime.UtcNow;
        public DateTime?  UpdatedAt { get; set; } = DateTime.UtcNow;
    }
}

Shop/Models/Kindergarten/KindergartenDetailsViewModel.cs
using Shop.Models.RealEstate;

namespace Shop.Models.Kindergarten
{
    public class KindergartenDetailsViewModel
    {
        public Guid? Id { get; set; }
        public string? GroupName { get; set; }
        public int? ChidlrenCount { get; set; }
        public string? KindergartenName { get; set; }
        public string? TeacherName { get; set; }
        public List<KindergartenImageViewModel> Image { get; set; }
            = new List<KindergartenImageViewModel>();
        public DateTime? CreatedAt { get; set; } = DateTime.UtcNow;
        public DateTime? UpdatedAt { get; set; } = DateTime.UtcNow;
    }
}

Shop/Models/Kindergarten/KindergartenImageViewModel.cs
namespace Shop.Models.Kindergarten
{
    public class KindergartenImageViewModel
    {
        public Guid Id { get; set; }
        public string? ImageTitle { get; set; }
        public byte[]? ImageData { get; set; }
        public string? Image { get; set; }
        public Guid? KindergartenId { get; set; }
    }
}

Shop/Models/Kindergarten/KindergartenIndexViewModel.cs
namespace Shop.Models.Kindergarten
{
    public class KindergartenIndexViewModel
    {
        public Guid? Id { get; set; }
        public string? GroupName { get; set; }
        public int? ChidlrenCount { get; set; }
        public string? KindergartenName { get; set; }
        public string? TeacherName { get; set; }
        public DateTime? CreatedAt { get; set; } = DateTime.UtcNow;
        public DateTime? UpdatedAt { get; set; } = DateTime.UtcNow;
    }
}

Shop/Models/Spaceships/ImageViewModel.cs
namespace Shop.Models.Spaceships
{
    public class ImageViewModel
    {
        public Guid ImageId { get; set; }
        public string? FilePath { get; set; }
        public Guid? SpaceshipId { get; set; }
    }
}

Shop/Controllers/KindergartenController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Data;
using Shop.Models.Kindergarten;
using Shop.Core.Dto;
using Shop.Core.ServiceInterface;
using Shop.ApplicationServices.Services;
using Shop.Models.Spaceships;
using Shop.Core.Domain;
using Shop.Models.RealEstate;
using Microsoft.EntityFrameworkCore;
using static System.Net.Mime.MediaTypeNames;


namespace Shop.Controllers
{
    public class KindergartenController : Controller
    {
        private readonly ShopContext _context;
        private readonly IKindergartenServices _kindergartenServices;

        public KindergartenController
            (
                ShopContext context,
                IKindergartenServices kindergartenServices
            )
        {
            _context = context;
            _kindergartenServices = kindergartenServices;
        }

        public IActionResult Index()
        {
            var result = _context.Kindergarten
                .Select(x => new KindergartenIndexViewModel
                {
                    Id = x.Id,
                    GroupName = x.GroupName,
                    ChidlrenCount = x.ChidlrenCount,
                    KindergartenName = x.KindergartenName,
                    TeacherName = x.TeacherName,
                    CreatedAt = x.CreatedAt,
                    UpdatedAt = x.UpdatedAt
                });

            return View(result);
        }
        
        [HttpGet]
        public IActionResult Create()
        {
            KindergartenCreateUpdateViewModel result = new();

            return View("CreateUpdate", result);
            
        }
        
        [HttpPost]
        public async Task<IActionResult> Create(KindergartenCreateUpdateViewModel vm)
        {
            var dto = new KindergartenDto()
            {
                GroupName = vm.GroupName,
                ChidlrenCount = vm.ChidlrenCount,
                KindergartenName = vm.KindergartenName,
                TeacherName = vm.TeacherName,
                Files = vm.Files,
                Image = vm.Image
                    .Select(x => new FileToDatabaseKindergartenDto
                    {
                        Id = x.Id,
                        ImageData = x.ImageData,
                        ImageTitle = x.ImageTitle,
                        KindergartenId = x.KindergartenId,
                    }).ToArray()
            };

            var result = await _kindergartenServices.Create(dto);

            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }



            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Update(Guid id)
        {
            var kindergarten = await _kindergartenServices.DetailAsync(id);

            if (kindergarten == null)
            {
                return NotFound();
            }
            KindergartenImageViewModel[] images = await FileFromDatabaseKindergarten(id);
            var vm = new KindergartenCreateUpdateViewModel();

            vm.Id = kindergarten.Id;
            vm.GroupName = kindergarten.GroupName;
            vm.ChidlrenCount = kindergarten.ChidlrenCount;
            vm.KindergartenName = kindergarten.KindergartenName;
            vm.TeacherName = kindergarten.TeacherName;
            vm.CreatedAt = kindergarten.CreatedAt;
            vm.UpdatedAt = kindergarten.UpdatedAt;
            vm.Image.AddRange(images);

            return View("CreateUpdate", vm);
        }

        [HttpPost]
        public async Task<IActionResult> Update(KindergartenCreateUpdateViewModel vm)
        {
            var dto = new KindergartenDto()
            {
                Id = (Guid)vm.Id,
                GroupName = vm.GroupName,
                ChidlrenCount = vm.ChidlrenCount,
                KindergartenName = vm.KindergartenName,
                TeacherName = vm.TeacherName,
            };

            var result = await _kindergartenServices.Update(dto); // Fix: Declare 'result' variable here  

            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)

        {
            var kindergarten = await _kindergartenServices.DetailAsync(id);

            if (kindergarten == null)
            {
                return NotFound();
            }
            KindergartenImageViewModel[] images = await FileFromDatabaseKindergarten(id);
            var vm = new KindergartenDeleteViewModel();

            vm.Id = kindergarten.Id;
            vm.GroupName = kindergarten.GroupName;
            vm.ChidlrenCount = kindergarten.ChidlrenCount;
            vm.TeacherName = kindergarten.TeacherName;
            vm.CreatedAt = kindergarten.CreatedAt;
            vm.UpdatedAt = kindergarten.UpdatedAt;
            vm.Image.AddRange(images);

            return View(vm);
        }
        [HttpPost]
        public async Task<IActionResult> DeleteConfirmation(Guid id)
        {
            var result = await _kindergartenServices.Delete(id);

            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {

            var kindergarten = await _kindergartenServices.DetailAsync(id);

            if (kindergarten == null)
            {
                return NotFound();
            }

            KindergartenImageViewModel[] images = await FileFromDatabaseKindergarten(id);

            var vm = new KindergartenDetailsViewModel();

            vm.Id = kindergarten.Id;
            vm.GroupName = kindergarten.GroupName;
            vm.ChidlrenCount = kindergarten.ChidlrenCount;
            vm.TeacherName = kindergarten.TeacherName;
            vm.KindergartenName = kindergarten.KindergartenName;
            vm.CreatedAt = kindergarten.CreatedAt;
            vm.UpdatedAt = kindergarten.UpdatedAt;
            vm.Image.AddRange(images);

            return View(vm);
        }
        private async Task<KindergartenImageViewModel[]> FileFromDatabaseKindergarten(Guid id)
        {
            return await _context.FileToDatabaseKindergartens
                .Where(x => x.KindergartenId == id)
                .Select(y => new KindergartenImageViewModel
                {
                    Id = y.Id,
                    KindergartenId = y.Id,
                    ImageData = y.ImageData,
                    ImageTitle = y.ImageTitle,
                    Image = string.Format("data:image/gif;base64,{0}", Convert.ToBase64String(y.ImageData))
                }).ToArrayAsync();
        }
        [HttpPost]
        public IActionResult DeleteFile(Guid fileId)
        {
            var file = _context.FileToDatabaseKindergartens
                .FirstOrDefault(f => f.Id == fileId);

            if (file == null)
            {
                return NotFound();
            }

            _context.FileToDatabaseKindergartens.Remove(file);
            _context.SaveChanges();

            // Suuna tagasi sama lasteaia muutmise vaatesse
            return RedirectToAction("Delete", new { id = file.KindergartenId });
        }
    }
}

Shop/Views/Kindergarten/CreateUpdate.cshtml
@model Shop.Models.Kindergarten.KindergartenCreateUpdateViewModel

@if (Model.Id.HasValue)
{
    <h1>Update</h1>
}
else
{
    <h1>Create</h1>
}

<div>
    <form method="post" enctype="multipart/form-data">
        <input asp-for="Id" type="hidden" />
        <input asp-for="CreatedAt" type="hidden" />
        <input asp-for="UpdatedAt" type="hidden" />

        <div class="form-group row">
            <label asp-for="GroupName" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input id="TestIdKindergartenGroupName" asp-for="GroupName" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="ChidlrenCount" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input id="TestIdKindergartenChidlrenCount" asp-for="ChidlrenCount" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="KindergartenName" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input id="TestIdKindergartenKindergartenName" asp-for="KindergartenName" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="TeacherName" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input id="TestIdKindergartenTeacherName" asp-for="TeacherName" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="CreatedAt" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="CreatedAt" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="UpdatedAt" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="UpdatedAt" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Files" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-5">
                <input class="form-control" asp-for="Files" multiple type="file" />
            </div>
        </div>

        <div>
            @foreach (var images in Model.Image)
            {
                <partial name="_Images" model="images " />
            }
        </div>

        @if (Model.Id.HasValue)
        {
            <input asp-action="update" asp-controller="Kindergarten" type="submit" class="btn btn-primary" id="TestIdKindergartenUpdate" value="Update" />
        }
        else
        {
            <input asp-action="create" asp-controller="Kindergarten" type="submit" class="btn btn-primary" id="TestIdKindergartenCreate" value="Create" />
        }

        <a asp-action="Index" asp-controller="Kindergarten" class="btn btn-success">Back</a>
    </form>
</div>

Shop/Views/Kindergarten/Delete.cshtml
@model Shop.Models.Kindergarten.KindergartenDeleteViewModel

<h1>Delete</h1>

<div>
	<h4>Kindergarten</h4>
    <dl class="row">
        <div class="form-group row">
            <label asp-for="Id" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Id)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="GroupName" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.GroupName)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="ChidlrenCount" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.ChidlrenCount)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="KindergartenName" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.KindergartenName)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="TeacherName" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.TeacherName)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="CreatedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.CreatedAt)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="UpdatedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.UpdatedAt)
        </div>
    </dl>
    <dl>
        @foreach (var images in Model.Image)
        {
            <partial name="_Images" model="images" />
        }
    </dl>
	<hr></hr>
	<form asp-action="DeleteConfirmation">
		<input type="hidden" asp-for="Id" />
		<input type="submit" value="Delete" class="btn btn-danger" id="TestIdKindergartenDelete" />
	</form>
	<a asp-action="Index" asp-controller="kindergarten" class="btn btn-success">Back</a>

</div>

Shop/Views/Kindergarten/Details.cshtml
@model Shop.Models.Kindergarten.KindergartenDetailsViewModel

<h1>Details</h1>

<div>
    <h4>Kindergarten</h4>
    <hr />
	<dl class="row">
		<div class="form-group row">
			<label asp-for="Id" class="col-sm-2 col-form-label"></label>
			<span class="col-sm-10">@Html.DisplayFor(model => model.Id)</span>
		</div>
	</dl>
	<dl class="row">
		<div class="form-group row">
			<label asp-for="GroupName" class="col-sm-2 col-form-label"></label>
			<span id="TestIdKindergartenGroupNameDetails" class="col-sm-10"> @Html.DisplayFor(model => model.GroupName) </span>
		</div>
	</dl>
	<dl class="row">
		<div class="form-group row">
			<label asp-for="ChidlrenCount" class="col-sm-2 col-form-label"></label>
			<span id="TestIdKindergartenChildrenCountDetails" class="col-sm-10"> @Html.DisplayFor(model => model.ChidlrenCount) </span>
		</div>
	</dl>
	<dl class="row">
		<div class="form-group row">
			<label asp-for="KindergartenName" class="col-sm-2 col-form-label"></label>
			<span id="TestIdKindergartenKindergartenNameDetails" class="col-sm-10"> @Html.DisplayFor(model => model.KindergartenName) </span>
		</div>
	</dl>
	<dl class="row">
		<div class="form-group row">
			<label asp-for="TeacherName" class="col-sm-2 col-form-label"></label>
			<span id="TestIdKindergartenTeacherNameDetails" class="col-sm-10"> @Html.DisplayFor(model => model.TeacherName) </span>
		</div>
	</dl>
	<dl class="row">
		<div class="form-group row">
			<label asp-for="CreatedAt" class="col-sm-2 col-form-label"></label>
			<span class="col-sm-10"> @Html.DisplayFor(model => model.CreatedAt) </span>
		</div>
	</dl>
	<dl class="row">
		<div class="form-group row">
			<label asp-for="UpdatedAt" class="col-sm-2 col-form-label"></label>
			<span class="col-sm-10">@Html.DisplayFor(model => model.UpdatedAt)</span>
		</div>
	</dl>

	@foreach (var images in Model.Image)
	{
		<partial name="_Images" model="images " />
	}

    <hr />
    <a asp-action="Index" asp-controller="kindergarten" class="btn btn-danger">Back</a>
</div>

Shop/Views/Kindergarten/Index.cshtml
@model IEnumerable<Shop.Models.Kindergarten.KindergartenIndexViewModel>

@{
	int rowNumber = 1;
}

<div>
	<a asp-action="create" asp-controller="Kindergarten" type="submit" class="btn btn-primary" id="TestIdCreate">Create</a>
</div>

<div class="h1">
	Kindergarten
</div>
<form method="post">
	<table class="table table-hover">
		<thead>
			<tr>
				<th scope="col"></th>
				<th scope="col">Group name</th>
				<th scope="col">Amount of children</th>
				<th scope="col">Kindergarten name</th>
				<th scope="col">Teacher name</th>
				<th scope="col"></th>
			</tr>
		</thead>
		<tbody>
			@foreach (var kindergarten in Model)
			{
				<tr>
					<td>@rowNumber</td>
					<td>@kindergarten.GroupName</td>
					<td>@kindergarten.ChidlrenCount</td>
					<td>@kindergarten.KindergartenName</td>
					<td>@kindergarten.TeacherName</td>
					
					<td>
						<a asp-action="update" asp-controller="Kindergarten" asp-route-id="@kindergarten.Id" class="btn btn-primary" id="TestIdUpdate">Update</a>
						<a asp-action="details" asp-controller="Kindergarten" asp-route-id="@kindergarten.Id" class="btn btn-primary" id="TestIdDetails">Details</a>
						<a asp-action="delete" asp-controller="Kindergarten" asp-route-id="@kindergarten.Id" class="btn btn-primary" id="TestIdDelete">Delete</a>
					</td>


				</tr>
				rowNumber += 1;
			}
		</tbody>
	</table>
</form>

Shop/Views/Kindergarten/_Images.cshtml
@model Shop.Models.Kindergarten.KindergartenImageViewModel

<div class="form-group row col-sm-4 offset-2">
	<div>@Model.ImageTitle</div>
	<img class="card-img-top" src="@Model.Image" asp-append-version="true" />

	 @if (ViewContext.RouteData.Values["action"]?.ToString() == "Delete")
    {
	<form asp-action="DeleteFile" asp-route-fileId="@Model.Id" method="post" style="margin-top:5px;">
		<button type="submit" class="btn btn-outline-danger btn-sm">Delete image</button>
	</form>
	}
</div>