Shop/Models/Spaceships/ImageViewModel.cs
namespace Shop.Models.Spaceships
{
    public class ImageViewModel
    {
        public Guid ImageId { get; set; }
        public string? FilePath { get; set; }
        public Guid? SpaceshipId { get; set; }
    }
}

Shop/Models/Spaceships/SpaceshipCreateUpdateViewModel.cs
using Shop.Core.Dto;

namespace Shop.Models.Spaceships
{
    public class SpaceshipCreateUpdateViewModel
    {
        public Guid? Id { get; set; }
        public string? Name { get; set; }

        public string? Classification { get; set; }
        public DateTime? BuildDate { get; set; }
        public int? Crew { get; set; }
        public int? EnginePower { get; set; }
        public List<IFormFile>? Files { get; set; }
        public List<ImageViewModel> Image { get; set; }
            = new List<ImageViewModel>();

        public DateTime? CreatedAt { get; set; }
        public DateTime? ModifiedAt { get; set; }
        
    }
}

Shop/Models/Spaceships/SpaceshipCreateViewModel.cs
namespace Shop.Models.Spaceships
{
    public class SpaceshipCreateViewModel
    {
        public Guid? Id { get; set; }
        public string? Name { get; set; }

        public string? Classification { get; set; }
        public DateTime? BuildDate { get; set; }
        public int? Crew { get; set; }
        public int? EnginePower { get; set; }

        public DateTime? CreatedAt { get; set; }
        public DateTime? ModifiedAt { get; set; }
    }
}

Shop/Models/Spaceships/SpaceshipDeleteViewModel.cs
namespace Shop.Models.Spaceships
{
    public class SpaceshipDeleteViewModel
    {
        public Guid? Id { get; set; }
        public string? Name { get; set; }

        public string? Classification { get; set; }
        public DateTime? BuildDate { get; set; }
        public int? Crew { get; set; }
        public int? EnginePower { get; set; }

        public List<ImageViewModel> Images { get; set; }
           = new List<ImageViewModel>();
        public DateTime? CreatedAt { get; set; }
        public DateTime? ModifiedAt { get; set; }
    }
}

Shop/Models/Spaceships/SpaceshipDetailsViewModel.cs
namespace Shop.Models.Spaceships
{
    public class SpaceshipDetailsViewModel
    {
        public Guid? Id { get; set; }
        public string? Name { get; set; }
        public string? Classification { get; set; }
        public DateTime? BuildDate { get; set; }
        public int? Crew { get; set; }
        public int? EnginePower { get; set; }
        public List<ImageViewModel> Images { get; set; }
           = new List<ImageViewModel>();

        public DateTime? CreatedAt { get; set; }
        public DateTime? ModifiedAt { get; set; }
    }
}

Shop/Models/Spaceships/SpaceshipIndexViewModel.cs
namespace Shop.Models.Spaceships
{
    public class SpaceshipIndexViewModel
    {

        public Guid? Id { get; set; }
        public string? Name { get; set; }

        public string? Classification { get; set; }
        public DateTime? BuildDate { get; set; }
        public int? Crew { get; set; }
        public int? EnginePower { get; set; }
        public List<ImageViewModel> Images { get; set; }
             = new List<ImageViewModel>();

    }
}

Shop/Controllers/SpaceshipsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Infrastructure;
using Shop.Core.Dto;
using Shop.Core.ServiceInterface;
using Shop.Data;
using Shop.Models.Spaceships;
using Shop.Core.Domain;
using Microsoft.EntityFrameworkCore;
using Shop.ApplicationServices.Services;
using Microsoft.AspNetCore.Authorization;

namespace Shop.Controllers
{
    public class SpaceshipsController : Controller
    {
        private readonly ShopContext _context;
        private readonly ISpaceshipServices _spaceshipServices;
        private readonly IFileServices _fileServices;
        public SpaceshipsController
            (
                ShopContext context,
                ISpaceshipServices spaceshipServices,
                IFileServices fileServices
            )
        {
            _context = context;
            _spaceshipServices = spaceshipServices;
            _fileServices = fileServices;

        }

        public async Task<IActionResult> Index()
        {
            var result = await _context.Spaceships
                .Select(x => new SpaceshipIndexViewModel
                {
                    Id = x.Id,
                    Name = x.Name,
                    Classification = x.Classification,
                    BuildDate = x.BuildDate,
                    Crew = x.Crew,
                    Images = _context.FileToApis
                        .Where(img => img.SpaceshipId == x.Id)
                        .Select(img => new ImageViewModel
                        {
                            FilePath = img.ExistingFilePath,
                            ImageId = img.Id
                        }).ToList()
                }).ToListAsync(); 

            return View(result);
        }
        [HttpGet]
        public IActionResult Create()
        {
            SpaceshipCreateUpdateViewModel result = new();

            return View("CreateUpdate", result);
        }
        [HttpPost]
        public async Task<IActionResult> Create(SpaceshipCreateUpdateViewModel vm)
        {
            var dto = new SpaceshipDto()
            {
                Id = vm.Id,
                Name = vm.Name,
                Classification = vm.Classification,
                BuildDate = vm.BuildDate,
                Crew = vm.Crew,
                EnginePower = vm.EnginePower,
                CreatedAt = vm.CreatedAt,
                ModifiedAt = vm.ModifiedAt,
                Files = vm.Files,
                FileToApiDtos = vm.Image
                    .Select(x => new FileToApiDto
                    {
                        Id = x.ImageId,
                        ExistingFilePath = x.FilePath,
                        SpaceshipId = x.SpaceshipId
                    }).ToArray()
            };

            var result = await _spaceshipServices.Create(dto);

            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Update(Guid id)
        {
            var spaceship = await _spaceshipServices.DetailAsync(id);

            if (spaceship == null)
            {
                return NotFound();
            }

            var images = await _context.FileToApis
               .Where(x => x.SpaceshipId == id)
               .Select(y => new ImageViewModel
               {
                   FilePath = y.ExistingFilePath,
                   ImageId = y.Id
               }).ToArrayAsync();

            var vm = new SpaceshipCreateUpdateViewModel();

            vm.Id = spaceship.Id;
            vm.Name = spaceship.Name;
            vm.Classification = spaceship.Classification;
            vm.BuildDate = spaceship.BuildDate;
            vm.Crew = spaceship.Crew;
            vm.EnginePower = spaceship.EnginePower;
            vm.CreatedAt = spaceship.CreatedAt;
            vm.ModifiedAt = spaceship.ModifiedAt;
            vm.Image.AddRange(images);

            return View("CreateUpdate", vm);
        }
        [HttpPost]
        public async Task<IActionResult> Update(SpaceshipCreateUpdateViewModel vm)
        {
            var dto = new SpaceshipDto()
            {
                Id = vm.Id,
                Name = vm.Name,
                Classification = vm.Classification,
                BuildDate = vm.BuildDate,
                Crew = vm.Crew,
                EnginePower = vm.EnginePower,
                CreatedAt = vm.CreatedAt,
                ModifiedAt = vm.ModifiedAt,
                Files = vm.Files,
                FileToApiDtos = vm.Image
                    .Select(x => new FileToApiDto
                    {
                        Id = x.ImageId,
                        ExistingFilePath = x.FilePath,
                        SpaceshipId = x.SpaceshipId
                    }).ToArray()
            };

            var result = await _spaceshipServices.Update(dto);

            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)

        { 
            var spaceship = await _spaceshipServices.DetailAsync(id);

            if (spaceship == null)
            {
                return NotFound();
            }
            var images = await _context.FileToApis
                .Where(x => x.SpaceshipId == id)
                .Select(y => new ImageViewModel
                {
                    FilePath = y.ExistingFilePath,
                    ImageId = y.Id
                }).ToArrayAsync();

            var vm = new SpaceshipDeleteViewModel();

            vm.Id = spaceship.Id;
            vm.Name = spaceship.Name;
            vm.Classification = spaceship.Classification;
            vm.BuildDate = spaceship.BuildDate;
            vm.Crew = spaceship.Crew;
            vm.EnginePower = spaceship.EnginePower;
            vm.CreatedAt = spaceship.CreatedAt;
            vm.ModifiedAt = spaceship.ModifiedAt;
            vm.Images.AddRange(images);

            return View(vm);
        }
        [HttpPost]
        public async Task<IActionResult> DeleteConfirmation(Guid id)
        {
            var result = await _spaceshipServices.Delete(id);

            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
           
            var spaceship = await _spaceshipServices.DetailAsync(id);

            if (spaceship == null)
            {
                return NotFound();
            }

            var images = await _context.FileToApis
                .Where(x => x.SpaceshipId == id)
                .Select(y => new ImageViewModel
                {
                    FilePath = y.ExistingFilePath,
                    ImageId = y.Id
                }).ToArrayAsync();

            var vm = new SpaceshipDetailsViewModel();

            vm.Id = spaceship.Id;
            vm.Name = spaceship.Name;
            vm.Classification = spaceship.Classification;
            vm.BuildDate = spaceship.BuildDate;
            vm.Crew = spaceship.Crew;
            vm.EnginePower = spaceship.EnginePower;
            vm.CreatedAt = spaceship.CreatedAt;
            vm.ModifiedAt = spaceship.ModifiedAt;
            vm.Images.AddRange(images);

            return View(vm);
        }
        public async Task<IActionResult> RemoveImage(ImageViewModel vm)
        {
            var dto = new FileToApiDto()
            {
                Id = vm.ImageId,
            };

            var images = await _fileServices.RemoveImageFromApi(dto);

            if (images == null)
            {
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

Shop/Views/Spaceships/Create.cshtml
@model Shop.Models.Spaceships.SpaceshipCreateViewModel

<h1>Create</h1>

<div>
    <form method="post" enctype="multipart/form-data">
        <input asp-for="Id" type="hidden" />
        <input asp-for="CreatedAt" type="hidden" />
        <input asp-for="ModifiedAt" type="hidden" />

        <div class="form-group row">
            <label asp-for="Name" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Name" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Classification" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Classification" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="BuildDate" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="BuildDate" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Crew" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Crew" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="EnginePower" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="EnginePower" class="form-control" />
            </div>
        </div>

        <input asp-action="create" asp-controller="spaceships" type="submit" class="btn btn-primary" value="Create" />
    </form>
</div>

Shop/Views/Spaceships/CreateUpdate.cshtml
@model Shop.Models.Spaceships.SpaceshipCreateUpdateViewModel

@if (Model.Id.HasValue)
{
    <h1>Update</h1>
}
else
{
    <h1>Create</h1>
}


<div>
    <form method="post" enctype="multipart/form-data">
        <input asp-for="Id" type="hidden" />
        <input asp-for="CreatedAt" type="hidden" />
        <input asp-for="ModifiedAt" type="hidden" />

        <div class="form-group row">
            <label asp-for="Name" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input id="TestIdName" asp-for="Name" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Classification" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input id="TestIdClassification" asp-for="Classification" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="BuildDate" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input id="TestIdBuildDate" asp-for="BuildDate" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Crew" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input id="TestIdCrew" asp-for="Crew" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="EnginePower" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input id="TestIdEnginPower" asp-for="EnginePower" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Files" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-5">
                <div class="custom-file">
                    <input class="form-control" asp-for="Files" multiple type="file" />
                </div>
            </div>
        </div>

        @foreach (var images in Model.Image)
        {
            <partial name="_Images" model="images" />
            <input asp-action="removeImage" asp-controller="spaceships" asp-route-imageId="@images.ImageId" type="submit" class="btn btn-success" value="Remove Image" />
          
        }


        @if (Model.Id.HasValue)
        {
            <input asp-action="update" asp-controller="spaceships" type="submit" class="btn btn-primary" id="TestIdSpaceshipUpdate" value="Update" />
        }
        else
        {
            <input asp-action="create" asp-controller="spaceships" type="submit" class="btn btn-primary" id="TestIdSpaceshipCreate" value="Create" />
        }

		<a asp-action="Index" asp-controller="spaceships" class="btn btn-success">Back</a>

    </form>
</div>

Shop/Views/Spaceships/Delete.cshtml
@model Shop.Models.Spaceships.SpaceshipDeleteViewModel

<h1>Delete</h1>

<div>
	<h4>Spaceship</h4>
	<hr> </hr>
	<dl class="row">
		<div class="form-group row">
			<label asp-for="Id" class="col-sm-2 col-form-label"></label>
			@Html.DisplayFor(model => model.Id)
		</div>
	</dl>
	<dl class="row">
		<div class="form-group row">
			<label asp-for="Name" class="col-sm-2 col-form-label"></label>
			@Html.DisplayFor(model => model.Name)
		</div>
	</dl>
	<dl class="row">
		<div class="form-group row">
			<label asp-for="Classification" class="col-sm-2 col-form-label"></label>
			@Html.DisplayFor(model => model.Classification)
		</div>
	</dl>
	<dl class="row">
		<div class="form-group row">
			<label asp-for="BuildDate" class="col-sm-2 col-form-label"></label>
			@Html.DisplayFor(model => model.BuildDate)
		</div>
	</dl>
	<dl class="row">
		<div class="form-group row">
			<label asp-for="Crew" class="col-sm-2 col-form-label"></label>
			@Html.DisplayFor(model => model.Crew)
		</div>
	</dl>
	<dl class="row">
		<div class="form-group row">
			<label asp-for="EnginePower" class="col-sm-2 col-form-label"></label>
			@Html.DisplayFor(model => model.EnginePower)
		</div>
	</dl>
	<dl class="row">
		<div class="form-group row">
			<label asp-for="CreatedAt" class="col-sm-2 col-form-label"></label>
			@Html.DisplayFor(model => model.CreatedAt)
		</div>
	</dl>
	<dl class="row">
		<div class="form-group row">
			<label asp-for="ModifiedAt" class="col-sm-2 col-form-label"></label>
			@Html.DisplayFor(model => model.ModifiedAt)
		</div>
	</dl>
	 @foreach (var images in Model.Images)
    {
        <partial name="_Images" model="images" />
    }

	<hr></hr>
	<form asp-action="DeleteConfirmation">
		<input type="hidden" asp-for="Id"/>
		<input type="submit" value="Delete" class="btn btn-danger" id="TestIdSpaceshipDelete" />
	</form>
	<a asp-action="Index" asp-controller="spaceships" class="btn btn-success">Back</a>

</div>


	

Shop/Views/Spaceships/Details.cshtml
@model Shop.Models.Spaceships.SpaceshipDetailsViewModel

<h1>Details</h1>

<div>
    <h4>Spaceships</h4>
    <hr />
    <dl class="row">
        <div class="form-group row">
            <label asp-for="Id" class="col-sm-2 col-form-label"></label>
            <span class="col-sm-10"> @Html.DisplayFor(model => model.Id) </span>
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="Name" class="col-sm-2 col-form-label"></label>
            <span id="TestIdNameDetails" class="col-sm-10"> @Html.DisplayFor(model => model.Name)</span>
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="Classification" class="col-sm-2 col-form-label"></label>
            <span id="TestIdClassificationDetails" class="col-sm-10"> @Html.DisplayFor(model => model.Classification) </span>
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="BuildDate" class="col-sm-2 col-form-label"></label>
            <span id="TestIdBuildDateDetails" class="col-sm-10"> @Html.DisplayFor(model => model.BuildDate) </span>
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="Crew" class="col-sm-2 col-form-label"></label>
            <span id="TestIdCrewDetails" class="col-sm-10"> @Html.DisplayFor(model => model.Crew) </span>
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="EnginePower" class="col-sm-2 col-form-label"></label>
            <span id="TestIdEnginePowerDetails" class="col-sm-10"> @Html.DisplayFor(model => model.EnginePower) </span>
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="CreatedAt" class="col-sm-2 col-form-label" id="TestIdCreatedAtDetails"></label>
            <span class="col-sm-10"> @Html.DisplayFor(model => model.CreatedAt) </span>
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="ModifiedAt" class="col-sm-2 col-form-label" id="TestIdModifiedAtDetails"></label>
            <span class="col-sm-10"> @Html.DisplayFor(model => model.ModifiedAt) </span>
        </div>
    </dl>

    @foreach (var images in Model.Images)
    {
        <partial name="_Images" model="images" />
    }

    <hr />
    <a asp-action="Index" asp-controller="spaceships" class="btn btn-danger" id="TestIdBackDetails">Back</a>
</div>

Shop/Views/Spaceships/Index.cshtml
@model IEnumerable<Shop.Models.Spaceships.SpaceshipIndexViewModel>

<div class="d-flex justify-content-between align-items-center mb-4">
    <h1 class="fw-bold m-0">Spaceships</h1>
    <a asp-action="create" asp-controller="Spaceships" class="btn btn-primary rounded-pill px-4 shadow-sm">
        <i class="bi bi-plus-lg me-1"></i> Create
    </a>
</div>

<div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
    @foreach (var ship in Model) 
    {
        <div class="col">
            <div class="card h-100 shadow-sm border-0 rounded-4 overflow-hidden">

                <div class="card-img-top-container bg-light" style="height: 200px; overflow: hidden;">
                    @if (ship.Images != null && ship.Images.Any())
                    {
                        <partial name="_Images" model="ship.Images.FirstOrDefault()" />
                    }
                    else
                    {
                        <div class="h-100 d-flex align-items-center justify-content-center text-muted">
                            <i class="bi bi-image" style="font-size: 2rem;"></i>
                        </div>
                    }
                </div>

                <div class="card-body">
                    <div class="d-flex justify-content-between align-items-start">
                        <h5 class="card-title fw-bold">@ship.Name</h5>
                        <span class="badge bg-primary-subtle text-primary rounded-pill">@ship.Classification</span>
                    </div>

                    <div class="mt-3 small text-muted">
                        <p class="mb-1"><i class="bi bi-calendar3 me-2"></i>@ship.BuildDate?.ToShortDateString()</p>
                        <p class="mb-0"><i class="bi bi-people me-2"></i>Crew: @ship.Crew</p>
                    </div>
                </div>

                <div class="card-footer bg-white border-0 p-3">
                    <div class="d-flex gap-2">
                        <a asp-action="Details" asp-route-id="@ship.Id" class="btn btn-light btn-sm flex-grow-1 rounded-3">Details</a>
                        <a asp-action="Update" asp-route-id="@ship.Id" class="btn btn-outline-secondary btn-sm rounded-3">Edit</a>
                        <a asp-action="Delete" asp-route-id="@ship.Id" class="btn btn-outline-danger btn-sm rounded-3">Delete</a>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

Shop/Views/Spaceships/_Images.cshtml
@model Shop.Models.Spaceships.ImageViewModel

@{
    var photoPaths = "~/multibleFileUpload/" + (Model.FilePath ?? "noimage.jpg");
}

<img class ="img-fluid-cover" src="@photoPaths" asp-append-version="true" />