Shop/Models/RealEstate/RealEstateCreateUpdateViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Shop.Models.RealEstate
{
    public class RealEstateCreateUpdateViewModel
    {
        public Guid? Id { get; set; }

        [Range(1, Double.PositiveInfinity, ErrorMessage = "Value cannot be negative")]
        public double? Area { get; set; }

        [Required]
        public string? Location { get; set; }

        [Range(1, 1000)]
        public int? RoomNumber { get; set; }
        public string? BuildingType { get; set; }
        public List<IFormFile>? Files { get; set; }
        public List<RealEstateImageViewModel> Image { get; set; }
            = new List<RealEstateImageViewModel>();

        public DateTime? CreatedAt { get; set; }
        public DateTime? ModifiedAt { get; set; }
    }
}

Shop/Models/RealEstate/RealEstateDeleteViewModel.cs
namespace Shop.Models.RealEstate
{
    public class RealEstateDeleteViewModel
    {
        public Guid? Id { get; set; }
        public double? Area { get; set; }
        public string? Location { get; set; }
        public int? RoomNumber { get; set; }
        public string? BuildingType { get; set; }
        public List<RealEstateImageViewModel> Image { get; set; }
           = new List<RealEstateImageViewModel>();

        public DateTime? CreatedAt { get; set; }
        public DateTime? ModifiedAt { get; set; }
    }
}

Shop/Models/RealEstate/RealEstateDetailsViewModel.cs
namespace Shop.Models.RealEstate
{
    public class RealEstateDetailsViewModel
    {
        public Guid? Id { get; set; }
        public double? Area { get; set; }
        public string? Location { get; set; }
        public int? RoomNumber { get; set; }
        public string? BuildingType { get; set; }

        public List<RealEstateImageViewModel> Image { get; set; }
            = new List<RealEstateImageViewModel>();
        public DateTime? CreatedAt { get; set; }
        public DateTime? ModifiedAt { get; set; }
    }
}

Shop/Models/RealEstate/RealEstateImageViewModel.cs
namespace Shop.Models.RealEstate
{
    public class RealEstateImageViewModel
    {
        public Guid Id { get; set; }
        public string? ImageTitle { get; set; }
        public byte[]? ImageData { get; set; }
        public string? Image { get; set; }
        public Guid? RealEstateId { get; set; }
    }
}

Shop/Models/RealEstate/RealEstateIndexViewModel.cs
namespace Shop.Models.RealEstate
{
    public class RealEstateIndexViewModel
    {
        public Guid? Id { get; set; }
        public double? Area { get; set; }
        public string? Location { get; set; }
        public int? RoomNumber { get; set; }
        public string? BuildingType { get; set; }

        public DateTime? CreatedAt { get; set; }
        public DateTime? ModifiedAt { get; set; }
    }
}

Shop/Models/Spaceships/ImageViewModel.cs
namespace Shop.Models.Spaceships
{
    public class ImageViewModel
    {
        public Guid ImageId { get; set; }
        public string? FilePath { get; set; }
        public Guid? SpaceshipId { get; set; }
    }
}

Shop/Controllers/RealEstateController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Shop.Data;
using Shop.Models.RealEstate;
using Shop.Core.Domain;
using Shop.Core.ServiceInterface;
using Shop.Models.Spaceships;
using Shop.ApplicationServices.Services;
using Shop.Core.Dto;
using AspNetCoreGeneratedDocument;

namespace Shop.Controllers
{
    public class RealEstateController : Controller
    {
        private readonly ShopContext _context;
        private readonly IRealEstateServices _realEstateServices;

        public RealEstateController
           (
               ShopContext context,
                IRealEstateServices realEstateServices
           )
        {
            _context = context;
            _realEstateServices = realEstateServices;
        }

        public IActionResult Index()
        {
            var result = _context.RealEstate
                .Select(x => new RealEstateIndexViewModel
                {
                    Id = x.Id,
                    Area = x.Area,
                    Location = x.Location,
                    RoomNumber = x.RoomNumber,
                    BuildingType = x.BuildingType,
                    CreatedAt = x.CreatedAt,
                    ModifiedAt = x.ModifiedAt
                });


            return View(result);
        }
        [HttpGet]
        public IActionResult Create()
        {
            RealEstateCreateUpdateViewModel result = new();

            return View("CreateUpdate", result);
        }
        [HttpPost]
        public async Task<IActionResult> Create(RealEstateCreateUpdateViewModel vm)
        {
            if(!ModelState.IsValid)
            {
                return View("CreateUpdate", vm);
            }

            var dto = new RealEstateDto()
            {
                Id = vm.Id,
                Area = vm.Area,
                Location = vm.Location,
                RoomNumber = vm.RoomNumber,
                BuildingType = vm.BuildingType,
                CreatedAt = vm.CreatedAt,
                ModifiedAt = vm.ModifiedAt,
                Files = vm.Files,
                Image = vm.Image
                    .Select(x => new FileToDatabaseDto
                    {
                        Id = x.Id,
                        ImageData = x.ImageData,
                        ImageTitle = x.ImageTitle,
                        RealEstateId = x.RealEstateId,
                    }).ToArray()
            };

            var result = await _realEstateServices.Create(dto);

            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public async Task<IActionResult> Update(Guid id)
        {
            var realEstate = await _realEstateServices.DetailAsync(id);

            if (realEstate == null)
            {
                return NotFound();
            }

            RealEstateImageViewModel[] images = await FileFromDatabase(id);

            var vm = new RealEstateCreateUpdateViewModel();

            vm.Id = realEstate.Id;
            vm.Area = realEstate.Area;
            vm.Location = realEstate.Location;
            vm.RoomNumber = realEstate.RoomNumber;
            vm.BuildingType = realEstate.BuildingType;
            vm.CreatedAt = realEstate.CreatedAt;
            vm.ModifiedAt = realEstate.ModifiedAt;
            vm.Image.AddRange(images);

            return View("CreateUpdate", vm);
        }
        [HttpPost]
        public async Task<IActionResult> Update(RealEstateCreateUpdateViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                return View("CreateUpdate", vm);
            }

            var dto = new RealEstateDto()
            {
                Id = vm.Id,
                Area = vm.Area,
                Location = vm.Location,
                RoomNumber = vm.RoomNumber,
                BuildingType = vm.BuildingType,
                CreatedAt = vm.CreatedAt,
                ModifiedAt = vm.ModifiedAt,
            };

            var result = await _realEstateServices.Update(dto);

            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)

        {
            var realEstate = await _realEstateServices.DetailAsync(id);

            if (realEstate == null)
            {
                return NotFound();
            }

            RealEstateImageViewModel[] images = await FileFromDatabase(id);

            var vm = new RealEstateDeleteViewModel();

            vm.Id = realEstate.Id;
            vm.Area = realEstate.Area;
            vm.Location = realEstate.Location;
            vm.RoomNumber = realEstate.RoomNumber;
            vm.BuildingType = realEstate.BuildingType;
            vm.CreatedAt = realEstate.CreatedAt;
            vm.ModifiedAt = realEstate.ModifiedAt;
            vm.Image.AddRange(images);

            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmation(Guid id)
        {
            var result = await _realEstateServices.Delete(id);

            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {

            var realEstate = await _realEstateServices.DetailAsync(id);

            if (realEstate == null)
            {
                return View("ItemNotFound", id);
            }
       

            RealEstateImageViewModel[] images = await FileFromDatabase(id);

            var vm = new RealEstateDetailsViewModel();

            vm.Id = realEstate.Id;
            vm.Area = realEstate.Area;
            vm.Location = realEstate.Location;
            vm.RoomNumber = realEstate.RoomNumber;
            vm.BuildingType = realEstate.BuildingType;
            vm.CreatedAt = realEstate.CreatedAt;
            vm.ModifiedAt = realEstate.ModifiedAt;
            vm.Image.AddRange(images);

            return View(vm);
        }

        private async Task<RealEstateImageViewModel[]> FileFromDatabase(Guid id)
        {
            return await _context.FileToDatabases
                .Where(x => x.RealEstateId == id)
                .Select(y => new RealEstateImageViewModel
                {
                    Id = y.Id,
                    RealEstateId = y.Id,
                    ImageData = y.ImageData,
                    ImageTitle = y.ImageTitle,
                    Image = string.Format("data:image/gif;base64,{0}", Convert.ToBase64String(y.ImageData))
                }).ToArrayAsync();
        }
        [HttpPost]
        public IActionResult DeleteFile(Guid Id)
        {
            var file = _context.FileToDatabases
                .FirstOrDefault(f => f.Id == Id);

            if (file == null)
            {
                return NotFound();
            }

            _context.FileToDatabases.Remove(file);
            _context.SaveChanges();

            // Returns to the same view
            return RedirectToAction("Delete", new { id = file.RealEstateId });
        }
    }
}

Shop/Views/RealEstate/CreateUpdate.cshtml
@model Shop.Models.RealEstate.RealEstateCreateUpdateViewModel

@if (Model.Id.HasValue)
{
    <h1>Update</h1>
}
else
{
    <h1>Create</h1>
}


<div>
    <form method="post" enctype="multipart/form-data">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input asp-for="Id" type="hidden" />
        <input asp-for="CreatedAt" type="hidden" />
        <input asp-for="ModifiedAt" type="hidden" />

        <div class="form-group row">
            <label asp-for="Area" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Area" class="form-control" />
				<span asp-validation-for="Area" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Location" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Location" class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="RoomNumber" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="RoomNumber" class="form-control" />
				<span asp-validation-for="RoomNumber" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="BuildingType" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="BuildingType" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="CreatedAt" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="CreatedAt" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Files" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-5">
                <input class="form-control" asp-for="Files" multiple type="file" />
            </div>
        </div>

        <div>
            @foreach (var images in Model.Image)
            {
                <partial name="_Images" model="images " />
            }
        </div>

        @if (Model.Id.HasValue)
        {
            <input asp-action="update" asp-controller="RealEstate" type="submit" class="btn btn-primary" value="Update" />
        }
        else
        {
            <input asp-action="create" asp-controller="RealEstate" type="submit" class="btn btn-primary" value="Create" />
        }

        <a asp-action="Index" asp-controller="RealEstate" class="btn btn-success">Back</a>

    </form>
</div>

Shop/Views/RealEstate/Delete.cshtml
@model Shop.Models.RealEstate.RealEstateDeleteViewModel

<h1>Delete</h1>

<div>
	<h4>Real Estate</h4>
    <hr />
    <dl class="row">
        <div class="form-group row">
            <label asp-for="Id" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Id)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="Area" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Area)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="Location" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Location)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="RoomNumber" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.RoomNumber)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="BuildingType" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.BuildingType)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="CreatedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.CreatedAt)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="ModifiedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.ModifiedAt)
        </div>
    </dl>
    <dl>
        @foreach (var images in Model.Image)
        {
            <partial name="_Images" model="images" />
        }
    </dl>

	<hr></hr>
	<form asp-action="DeleteConfirmation">
		<input type="hidden" asp-for="Id" />
		<input type="submit" value="Delete" class="btn btn-danger" />
	</form>
	<a asp-action="Index" asp-controller="RealEstate" class="btn btn-success">Back</a>

</div>

Shop/Views/RealEstate/Details.cshtml
@model Shop.Models.RealEstate.RealEstateDetailsViewModel

<h1>Details</h1>

<div>
    <h4>Real Estate</h4>
    <hr />
    <dl class="row">
        <div class="form-group row">
            <label asp-for="Id" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Id)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="Area" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Area)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="Location" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Location)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="RoomNumber" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.RoomNumber)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="BuildingType" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.BuildingType)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="CreatedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.CreatedAt)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="ModifiedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.ModifiedAt)
        </div>
    </dl>

    <div class="row mt-4">
        <div class="col-md-10 offset-md-1">
            <div class="d-flex flex-wrap gap-3">
                @foreach (var images in Model.Image)
                {
                    <partial name="_Images" model="images " />
                }
            </div>
        </div>
    </div>
    

    <hr />
    <a asp-action="Index" asp-controller="RealEstate" class="btn btn-danger">Back</a>
</div>

Shop/Views/RealEstate/Index.cshtml
@using Shop.Core.Domain
@using Shop.Data.Migrations
@model IEnumerable<Shop.Models.RealEstate.RealEstateIndexViewModel>

@{
	int rowNumber = 1;
}

<div>
	<a asp-action="create" asp-controller="RealEstate" type="submit" class="btn btn-primary">Create</a>
</div>

<div class="h1">
	Real Estate
</div>
<form method="post">
	<table class="table table-hover">
		<thead>
			<tr>
				<th scope="col">Nr</th>
				<th scope="col">Area</th>
				<th scope="col">Location</th>
				<th scope="col">Room Number</th>
				<th scope="col">Building Type</th>
				<th scope="col">Created At</th>
				<th scope="col"></th>
			</tr>
		</thead>
		<tbody>
			@foreach (var realEstate in Model)
			{
				<tr>
					<td>@rowNumber</td>
					<td>@realEstate.Area</td>
					<td>@realEstate.Location</td>
					<td>@realEstate.RoomNumber</td>
					<td>@realEstate.BuildingType</td>
					<td>@realEstate.CreatedAt</td>

					<td>
						<a asp-action="update" asp-controller="RealEstate" asp-route-id="@realEstate.Id" class="btn btn-outline-primary">Update</a>
						<a asp-action="delete" asp-controller="RealEstate" asp-route-id="@realEstate.Id" class="btn btn-outline-danger">Delete</a>
						<a asp-action="details" asp-controller="RealEstate" asp-route-id="@realEstate.Id" class="btn btn-primary">Details</a>
					</td>


				</tr>
				rowNumber += 1;
			}
		</tbody>
	</table>
</form>

Shop/Views/RealEstate/ItemNotFound.cshtml
@model Guid

@{
    ViewData["Title"] = "Not Found";
}

<h1>Item Not Found with Id: </h1> 
<p>@Model</p>
<p>The item you are looking for does not exist.</p>

<a asp-action="Index" asp-controller="Home" class="btn btn-primary">Home</a>

Shop/Views/RealEstate/_Images.cshtml
@model Shop.Models.RealEstate.RealEstateImageViewModel

<div class="form-group row col-sm-4 offset-2">
    <div>@Model.ImageTitle</div>
    <img class="card-img-top" src="@Model.Image" asp-append-version="true" />
	@if (ViewContext.RouteData.Values["action"]?.ToString() == "Delete")
	{
		<form asp-action="DeleteFile" asp-route-id="@Model.Id" method="post" style="margin-top:5px;">
			<button type="submit" class="btn btn-outline-danger btn-sm">Delete image</button>
		</form>
	}
</div>